[package]
name = "gensurvey"
version = "0.1.2"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
regex = "1"
thiserror = "1"
htmlescape = "0.3"
clap = { version = "4", features = ["derive"] }
